############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Teaching"
url = "/teaching"
weight = 3

[[main]]
name = "Research"
url = "/research"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
